//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermsAndDefinitions.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TermsAndDefinitions.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a
        ///about
        ///above
        ///after
        ///again
        ///against
        ///all
        ///am
        ///an
        ///and
        ///any
        ///are
        ///aren
        ///as
        ///at
        ///be
        ///because
        ///been
        ///before
        ///being
        ///below
        ///between
        ///both
        ///but
        ///by
        ///can
        ///t
        ///cannot
        ///could
        ///couldn
        ///did
        ///didn
        ///do
        ///does
        ///doesn
        ///doing
        ///don
        ///down
        ///during
        ///each
        ///few
        ///for
        ///from
        ///further
        ///had
        ///hadn
        ///has
        ///hasn
        ///have
        ///haven
        ///having
        ///he
        ///d
        ///ll
        ///s
        ///her
        ///here
        ///hers
        ///herself
        ///him
        ///himself
        ///his
        ///how
        ///i
        ///m
        ///ve
        ///if
        ///in
        ///into
        ///is
        ///isn
        ///it
        ///its
        ///itself
        ///me
        ///more
        ///most
        ///mustn
        ///my
        ///myself
        ///no
        ///nor
        ///not
        ///of
        ///off
        ///on
        ///once
        ///only
        ///or
        ///other
        ///ought
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EnglishStopwords {
            get {
                return ResourceManager.GetString("EnglishStopwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на а
        ///е
        ///и
        ///ж
        ///м
        ///о
        ///на
        ///не
        ///ни
        ///об
        ///но
        ///он
        ///мне
        ///мои
        ///мож
        ///она
        ///они
        ///оно
        ///мной
        ///много
        ///многочисленное
        ///многочисленная
        ///многочисленные
        ///многочисленный
        ///мною
        ///мой
        ///мог
        ///могут
        ///можно
        ///может
        ///можхо
        ///мор
        ///моя
        ///моё
        ///мочь
        ///над
        ///нее
        ///оба
        ///нам
        ///нем
        ///нами
        ///ними
        ///мимо
        ///немного
        ///одной
        ///одного
        ///менее
        ///однажды
        ///однако
        ///меня
        ///нему
        ///меньше
        ///ней
        ///наверху
        ///него
        ///ниже
        ///мало
        ///надо
        ///один
        ///одиннадцать
        ///одиннадцатый
        ///назад
        ///наиболее
        ///недавно
        ///миллионов
        ///недалеко
        ///между
        ///низко
        ///меля
        ///нельзя
        ///нибудь
        ///непрерывно
        ///наконец
        ///никогда
        ///ник [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RussianStopwords {
            get {
                return ResourceManager.GetString("RussianStopwords", resourceCulture);
            }
        }
    }
}
