//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermsAndDefinitions.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public int IdDefinition { get; set; }
        public int IdTerm { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
    
        public virtual Term Term { get; set; }
    }
}
