//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermsAndDefinitions.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.Definitions = new HashSet<Definition>();
            this.Projects = new HashSet<Project>();
        }
    
        public int IdTerm { get; set; }
        public string TermName { get; set; }
        public Nullable<int> IdFundamentalArea { get; set; }
    
        public virtual ICollection<Definition> Definitions { get; set; }
        public virtual FundamentalArea FundamentalArea { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
